package com.jackpf.apkdownloader.Proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Play.proto

public final class Play {
  private Play() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestContextOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .App app = 1;
    /**
     * <code>repeated .App app = 1;</code>
     */
    java.util.List<Play.App> 
        getAppList();
    /**
     * <code>repeated .App app = 1;</code>
     */
    Play.App getApp(int index);
    /**
     * <code>repeated .App app = 1;</code>
     */
    int getAppCount();
    /**
     * <code>repeated .App app = 1;</code>
     */
    java.util.List<? extends Play.AppOrBuilder> 
        getAppOrBuilderList();
    /**
     * <code>repeated .App app = 1;</code>
     */
    Play.AppOrBuilder getAppOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestContext}
   */
  public static final class RequestContext extends
      com.google.protobuf.GeneratedMessage
      implements RequestContextOrBuilder {
    // Use RequestContext.newBuilder() to construct.
    private RequestContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestContext(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestContext defaultInstance;
    public static RequestContext getDefaultInstance() {
      return defaultInstance;
    }

    public RequestContext getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestContext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                app_ = new java.util.ArrayList<Play.App>();
                mutable_bitField0_ |= 0x00000001;
              }
              app_.add(input.readMessage(Play.App.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          app_ = java.util.Collections.unmodifiableList(app_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Play.internal_static_RequestContext_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Play.internal_static_RequestContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Play.RequestContext.class, Play.RequestContext.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestContext> PARSER =
        new com.google.protobuf.AbstractParser<RequestContext>() {
      public RequestContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestContext(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestContext> getParserForType() {
      return PARSER;
    }

    // repeated .App app = 1;
    public static final int APP_FIELD_NUMBER = 1;
    private java.util.List<Play.App> app_;
    /**
     * <code>repeated .App app = 1;</code>
     */
    public java.util.List<Play.App> getAppList() {
      return app_;
    }
    /**
     * <code>repeated .App app = 1;</code>
     */
    public java.util.List<? extends Play.AppOrBuilder> 
        getAppOrBuilderList() {
      return app_;
    }
    /**
     * <code>repeated .App app = 1;</code>
     */
    public int getAppCount() {
      return app_.size();
    }
    /**
     * <code>repeated .App app = 1;</code>
     */
    public Play.App getApp(int index) {
      return app_.get(index);
    }
    /**
     * <code>repeated .App app = 1;</code>
     */
    public Play.AppOrBuilder getAppOrBuilder(
        int index) {
      return app_.get(index);
    }

    private void initFields() {
      app_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < app_.size(); i++) {
        output.writeMessage(1, app_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < app_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, app_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Play.RequestContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Play.RequestContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Play.RequestContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Play.RequestContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Play.RequestContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Play.RequestContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Play.RequestContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Play.RequestContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Play.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Play.RequestContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Play.RequestContext prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Play.RequestContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Play.internal_static_RequestContext_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Play.internal_static_RequestContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Play.RequestContext.class, Play.RequestContext.Builder.class);
      }

      // Construct using Play.RequestContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (appBuilder_ == null) {
          app_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Play.internal_static_RequestContext_descriptor;
      }

      public Play.RequestContext getDefaultInstanceForType() {
        return Play.RequestContext.getDefaultInstance();
      }

      public Play.RequestContext build() {
        Play.RequestContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Play.RequestContext buildPartial() {
        Play.RequestContext result = new Play.RequestContext(this);
        int from_bitField0_ = bitField0_;
        if (appBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            app_ = java.util.Collections.unmodifiableList(app_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.app_ = app_;
        } else {
          result.app_ = appBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Play.RequestContext) {
          return mergeFrom((Play.RequestContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Play.RequestContext other) {
        if (other == Play.RequestContext.getDefaultInstance()) return this;
        if (appBuilder_ == null) {
          if (!other.app_.isEmpty()) {
            if (app_.isEmpty()) {
              app_ = other.app_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppIsMutable();
              app_.addAll(other.app_);
            }
            onChanged();
          }
        } else {
          if (!other.app_.isEmpty()) {
            if (appBuilder_.isEmpty()) {
              appBuilder_.dispose();
              appBuilder_ = null;
              app_ = other.app_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAppFieldBuilder() : null;
            } else {
              appBuilder_.addAllMessages(other.app_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Play.RequestContext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Play.RequestContext) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .App app = 1;
      private java.util.List<Play.App> app_ =
        java.util.Collections.emptyList();
      private void ensureAppIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          app_ = new java.util.ArrayList<Play.App>(app_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Play.App, Play.App.Builder, Play.AppOrBuilder> appBuilder_;

      /**
       * <code>repeated .App app = 1;</code>
       */
      public java.util.List<Play.App> getAppList() {
        if (appBuilder_ == null) {
          return java.util.Collections.unmodifiableList(app_);
        } else {
          return appBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public int getAppCount() {
        if (appBuilder_ == null) {
          return app_.size();
        } else {
          return appBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Play.App getApp(int index) {
        if (appBuilder_ == null) {
          return app_.get(index);
        } else {
          return appBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder setApp(
          int index, Play.App value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.set(index, value);
          onChanged();
        } else {
          appBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder setApp(
          int index, Play.App.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.set(index, builderForValue.build());
          onChanged();
        } else {
          appBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder addApp(Play.App value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.add(value);
          onChanged();
        } else {
          appBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder addApp(
          int index, Play.App value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.add(index, value);
          onChanged();
        } else {
          appBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder addApp(
          Play.App.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.add(builderForValue.build());
          onChanged();
        } else {
          appBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder addApp(
          int index, Play.App.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.add(index, builderForValue.build());
          onChanged();
        } else {
          appBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder addAllApp(
          java.lang.Iterable<? extends Play.App> values) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          super.addAll(values, app_);
          onChanged();
        } else {
          appBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder clearApp() {
        if (appBuilder_ == null) {
          app_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Builder removeApp(int index) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.remove(index);
          onChanged();
        } else {
          appBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Play.App.Builder getAppBuilder(
          int index) {
        return getAppFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Play.AppOrBuilder getAppOrBuilder(
          int index) {
        if (appBuilder_ == null) {
          return app_.get(index);  } else {
          return appBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public java.util.List<? extends Play.AppOrBuilder> 
           getAppOrBuilderList() {
        if (appBuilder_ != null) {
          return appBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(app_);
        }
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Play.App.Builder addAppBuilder() {
        return getAppFieldBuilder().addBuilder(
            Play.App.getDefaultInstance());
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public Play.App.Builder addAppBuilder(
          int index) {
        return getAppFieldBuilder().addBuilder(
            index, Play.App.getDefaultInstance());
      }
      /**
       * <code>repeated .App app = 1;</code>
       */
      public java.util.List<Play.App.Builder> 
           getAppBuilderList() {
        return getAppFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Play.App, Play.App.Builder, Play.AppOrBuilder> 
          getAppFieldBuilder() {
        if (appBuilder_ == null) {
          appBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Play.App, Play.App.Builder, Play.AppOrBuilder>(
                  app_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          app_ = null;
        }
        return appBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RequestContext)
    }

    static {
      defaultInstance = new RequestContext(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestContext)
  }

  public interface AppOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes authSubToken = 1;
    /**
     * <code>optional bytes authSubToken = 1;</code>
     *
     * <pre>
     * authsub token for service 'android'
     * </pre>
     */
    boolean hasAuthSubToken();
    /**
     * <code>optional bytes authSubToken = 1;</code>
     *
     * <pre>
     * authsub token for service 'android'
     * </pre>
     */
    com.google.protobuf.ByteString getAuthSubToken();

    // optional bool isSecure = 2;
    /**
     * <code>optional bool isSecure = 2;</code>
     *
     * <pre>
     * is this a secure request or not
     * </pre>
     */
    boolean hasIsSecure();
    /**
     * <code>optional bool isSecure = 2;</code>
     *
     * <pre>
     * is this a secure request or not
     * </pre>
     */
    boolean getIsSecure();

    // optional int32 version = 3;
    /**
     * <code>optional int32 version = 3;</code>
     *
     * <pre>
     * always 1002
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 3;</code>
     *
     * <pre>
     * always 1002
     * </pre>
     */
    int getVersion();

    // optional string androidId = 4;
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    boolean hasAndroidId();
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    java.lang.String getAndroidId();
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    com.google.protobuf.ByteString
        getAndroidIdBytes();

    // optional string deviceAndSdkVersion = 5;
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    boolean hasDeviceAndSdkVersion();
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    java.lang.String getDeviceAndSdkVersion();
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceAndSdkVersionBytes();

    // optional string userLanguage = 6;
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    boolean hasUserLanguage();
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    java.lang.String getUserLanguage();
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserLanguageBytes();

    // optional string userCountry = 7;
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    boolean hasUserCountry();
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    java.lang.String getUserCountry();
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserCountryBytes();

    // optional string operatorAlpha = 8;
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    boolean hasOperatorAlpha();
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    java.lang.String getOperatorAlpha();
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    com.google.protobuf.ByteString
        getOperatorAlphaBytes();

    // optional string simOperatorAlpha = 9;
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    boolean hasSimOperatorAlpha();
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    java.lang.String getSimOperatorAlpha();
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    com.google.protobuf.ByteString
        getSimOperatorAlphaBytes();

    // optional string operatorNumeric = 10;
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    boolean hasOperatorNumeric();
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    java.lang.String getOperatorNumeric();
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    com.google.protobuf.ByteString
        getOperatorNumericBytes();

    // optional string simOperatorNumeric = 11;
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    boolean hasSimOperatorNumeric();
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    java.lang.String getSimOperatorNumeric();
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    com.google.protobuf.ByteString
        getSimOperatorNumericBytes();
  }
  /**
   * Protobuf type {@code App}
   */
  public static final class App extends
      com.google.protobuf.GeneratedMessage
      implements AppOrBuilder {
    // Use App.newBuilder() to construct.
    private App(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private App(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final App defaultInstance;
    public static App getDefaultInstance() {
      return defaultInstance;
    }

    public App getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private App(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              authSubToken_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSecure_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              androidId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              deviceAndSdkVersion_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              userLanguage_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              userCountry_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              operatorAlpha_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              simOperatorAlpha_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              operatorNumeric_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              simOperatorNumeric_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Play.internal_static_App_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Play.internal_static_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Play.App.class, Play.App.Builder.class);
    }

    public static com.google.protobuf.Parser<App> PARSER =
        new com.google.protobuf.AbstractParser<App>() {
      public App parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new App(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<App> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes authSubToken = 1;
    public static final int AUTHSUBTOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString authSubToken_;
    /**
     * <code>optional bytes authSubToken = 1;</code>
     *
     * <pre>
     * authsub token for service 'android'
     * </pre>
     */
    public boolean hasAuthSubToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes authSubToken = 1;</code>
     *
     * <pre>
     * authsub token for service 'android'
     * </pre>
     */
    public com.google.protobuf.ByteString getAuthSubToken() {
      return authSubToken_;
    }

    // optional bool isSecure = 2;
    public static final int ISSECURE_FIELD_NUMBER = 2;
    private boolean isSecure_;
    /**
     * <code>optional bool isSecure = 2;</code>
     *
     * <pre>
     * is this a secure request or not
     * </pre>
     */
    public boolean hasIsSecure() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isSecure = 2;</code>
     *
     * <pre>
     * is this a secure request or not
     * </pre>
     */
    public boolean getIsSecure() {
      return isSecure_;
    }

    // optional int32 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>optional int32 version = 3;</code>
     *
     * <pre>
     * always 1002
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 version = 3;</code>
     *
     * <pre>
     * always 1002
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // optional string androidId = 4;
    public static final int ANDROIDID_FIELD_NUMBER = 4;
    private java.lang.Object androidId_;
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    public boolean hasAndroidId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    public java.lang.String getAndroidId() {
      java.lang.Object ref = androidId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          androidId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string androidId = 4;</code>
     *
     * <pre>
     * android id converted to hexadecimal
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAndroidIdBytes() {
      java.lang.Object ref = androidId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        androidId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string deviceAndSdkVersion = 5;
    public static final int DEVICEANDSDKVERSION_FIELD_NUMBER = 5;
    private java.lang.Object deviceAndSdkVersion_;
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    public boolean hasDeviceAndSdkVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    public java.lang.String getDeviceAndSdkVersion() {
      java.lang.Object ref = deviceAndSdkVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceAndSdkVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceAndSdkVersion = 5;</code>
     *
     * <pre>
     * ro.product.device ':' ro.build.version.sdk 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceAndSdkVersionBytes() {
      java.lang.Object ref = deviceAndSdkVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceAndSdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userLanguage = 6;
    public static final int USERLANGUAGE_FIELD_NUMBER = 6;
    private java.lang.Object userLanguage_;
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    public boolean hasUserLanguage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    public java.lang.String getUserLanguage() {
      java.lang.Object ref = userLanguage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userLanguage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userLanguage = 6;</code>
     *
     * <pre>
     * ro.product.locale.language
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserLanguageBytes() {
      java.lang.Object ref = userLanguage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userCountry = 7;
    public static final int USERCOUNTRY_FIELD_NUMBER = 7;
    private java.lang.Object userCountry_;
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    public boolean hasUserCountry() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    public java.lang.String getUserCountry() {
      java.lang.Object ref = userCountry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userCountry_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userCountry = 7;</code>
     *
     * <pre>
     * ro.product.locale.region
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserCountryBytes() {
      java.lang.Object ref = userCountry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCountry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string operatorAlpha = 8;
    public static final int OPERATORALPHA_FIELD_NUMBER = 8;
    private java.lang.Object operatorAlpha_;
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    public boolean hasOperatorAlpha() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    public java.lang.String getOperatorAlpha() {
      java.lang.Object ref = operatorAlpha_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operatorAlpha_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string operatorAlpha = 8;</code>
     *
     * <pre>
     * gsm.operator.alpha
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOperatorAlphaBytes() {
      java.lang.Object ref = operatorAlpha_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorAlpha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string simOperatorAlpha = 9;
    public static final int SIMOPERATORALPHA_FIELD_NUMBER = 9;
    private java.lang.Object simOperatorAlpha_;
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    public boolean hasSimOperatorAlpha() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    public java.lang.String getSimOperatorAlpha() {
      java.lang.Object ref = simOperatorAlpha_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          simOperatorAlpha_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string simOperatorAlpha = 9;</code>
     *
     * <pre>
     * gsm.sim.operator.alpha
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSimOperatorAlphaBytes() {
      java.lang.Object ref = simOperatorAlpha_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simOperatorAlpha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string operatorNumeric = 10;
    public static final int OPERATORNUMERIC_FIELD_NUMBER = 10;
    private java.lang.Object operatorNumeric_;
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    public boolean hasOperatorNumeric() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    public java.lang.String getOperatorNumeric() {
      java.lang.Object ref = operatorNumeric_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operatorNumeric_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string operatorNumeric = 10;</code>
     *
     * <pre>
     * gsm.operator.numeric
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOperatorNumericBytes() {
      java.lang.Object ref = operatorNumeric_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorNumeric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string simOperatorNumeric = 11;
    public static final int SIMOPERATORNUMERIC_FIELD_NUMBER = 11;
    private java.lang.Object simOperatorNumeric_;
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    public boolean hasSimOperatorNumeric() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    public java.lang.String getSimOperatorNumeric() {
      java.lang.Object ref = simOperatorNumeric_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          simOperatorNumeric_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string simOperatorNumeric = 11;</code>
     *
     * <pre>
     * sim.gsm.operator.numeric
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSimOperatorNumericBytes() {
      java.lang.Object ref = simOperatorNumeric_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simOperatorNumeric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      authSubToken_ = com.google.protobuf.ByteString.EMPTY;
      isSecure_ = false;
      version_ = 0;
      androidId_ = "";
      deviceAndSdkVersion_ = "";
      userLanguage_ = "";
      userCountry_ = "";
      operatorAlpha_ = "";
      simOperatorAlpha_ = "";
      operatorNumeric_ = "";
      simOperatorNumeric_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, authSubToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSecure_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAndroidIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDeviceAndSdkVersionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUserLanguageBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getUserCountryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getOperatorAlphaBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSimOperatorAlphaBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getOperatorNumericBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getSimOperatorNumericBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, authSubToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSecure_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAndroidIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDeviceAndSdkVersionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUserLanguageBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUserCountryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getOperatorAlphaBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSimOperatorAlphaBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getOperatorNumericBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getSimOperatorNumericBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Play.App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Play.App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Play.App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Play.App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Play.App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Play.App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Play.App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Play.App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Play.App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Play.App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Play.App prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Play.AppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Play.internal_static_App_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Play.internal_static_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Play.App.class, Play.App.Builder.class);
      }

      // Construct using Play.App.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        authSubToken_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        isSecure_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        androidId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceAndSdkVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        userLanguage_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        userCountry_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        operatorAlpha_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        simOperatorAlpha_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        operatorNumeric_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        simOperatorNumeric_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Play.internal_static_App_descriptor;
      }

      public Play.App getDefaultInstanceForType() {
        return Play.App.getDefaultInstance();
      }

      public Play.App build() {
        Play.App result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Play.App buildPartial() {
        Play.App result = new Play.App(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authSubToken_ = authSubToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSecure_ = isSecure_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.androidId_ = androidId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceAndSdkVersion_ = deviceAndSdkVersion_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.userLanguage_ = userLanguage_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.userCountry_ = userCountry_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.operatorAlpha_ = operatorAlpha_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.simOperatorAlpha_ = simOperatorAlpha_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.operatorNumeric_ = operatorNumeric_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.simOperatorNumeric_ = simOperatorNumeric_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Play.App) {
          return mergeFrom((Play.App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Play.App other) {
        if (other == Play.App.getDefaultInstance()) return this;
        if (other.hasAuthSubToken()) {
          setAuthSubToken(other.getAuthSubToken());
        }
        if (other.hasIsSecure()) {
          setIsSecure(other.getIsSecure());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasAndroidId()) {
          bitField0_ |= 0x00000008;
          androidId_ = other.androidId_;
          onChanged();
        }
        if (other.hasDeviceAndSdkVersion()) {
          bitField0_ |= 0x00000010;
          deviceAndSdkVersion_ = other.deviceAndSdkVersion_;
          onChanged();
        }
        if (other.hasUserLanguage()) {
          bitField0_ |= 0x00000020;
          userLanguage_ = other.userLanguage_;
          onChanged();
        }
        if (other.hasUserCountry()) {
          bitField0_ |= 0x00000040;
          userCountry_ = other.userCountry_;
          onChanged();
        }
        if (other.hasOperatorAlpha()) {
          bitField0_ |= 0x00000080;
          operatorAlpha_ = other.operatorAlpha_;
          onChanged();
        }
        if (other.hasSimOperatorAlpha()) {
          bitField0_ |= 0x00000100;
          simOperatorAlpha_ = other.simOperatorAlpha_;
          onChanged();
        }
        if (other.hasOperatorNumeric()) {
          bitField0_ |= 0x00000200;
          operatorNumeric_ = other.operatorNumeric_;
          onChanged();
        }
        if (other.hasSimOperatorNumeric()) {
          bitField0_ |= 0x00000400;
          simOperatorNumeric_ = other.simOperatorNumeric_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Play.App parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Play.App) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes authSubToken = 1;
      private com.google.protobuf.ByteString authSubToken_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes authSubToken = 1;</code>
       *
       * <pre>
       * authsub token for service 'android'
       * </pre>
       */
      public boolean hasAuthSubToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes authSubToken = 1;</code>
       *
       * <pre>
       * authsub token for service 'android'
       * </pre>
       */
      public com.google.protobuf.ByteString getAuthSubToken() {
        return authSubToken_;
      }
      /**
       * <code>optional bytes authSubToken = 1;</code>
       *
       * <pre>
       * authsub token for service 'android'
       * </pre>
       */
      public Builder setAuthSubToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        authSubToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes authSubToken = 1;</code>
       *
       * <pre>
       * authsub token for service 'android'
       * </pre>
       */
      public Builder clearAuthSubToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authSubToken_ = getDefaultInstance().getAuthSubToken();
        onChanged();
        return this;
      }

      // optional bool isSecure = 2;
      private boolean isSecure_ ;
      /**
       * <code>optional bool isSecure = 2;</code>
       *
       * <pre>
       * is this a secure request or not
       * </pre>
       */
      public boolean hasIsSecure() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isSecure = 2;</code>
       *
       * <pre>
       * is this a secure request or not
       * </pre>
       */
      public boolean getIsSecure() {
        return isSecure_;
      }
      /**
       * <code>optional bool isSecure = 2;</code>
       *
       * <pre>
       * is this a secure request or not
       * </pre>
       */
      public Builder setIsSecure(boolean value) {
        bitField0_ |= 0x00000002;
        isSecure_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSecure = 2;</code>
       *
       * <pre>
       * is this a secure request or not
       * </pre>
       */
      public Builder clearIsSecure() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSecure_ = false;
        onChanged();
        return this;
      }

      // optional int32 version = 3;
      private int version_ ;
      /**
       * <code>optional int32 version = 3;</code>
       *
       * <pre>
       * always 1002
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 version = 3;</code>
       *
       * <pre>
       * always 1002
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 3;</code>
       *
       * <pre>
       * always 1002
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 3;</code>
       *
       * <pre>
       * always 1002
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      // optional string androidId = 4;
      private java.lang.Object androidId_ = "";
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public boolean hasAndroidId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public java.lang.String getAndroidId() {
        java.lang.Object ref = androidId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          androidId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAndroidIdBytes() {
        java.lang.Object ref = androidId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          androidId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public Builder setAndroidId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        androidId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public Builder clearAndroidId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        androidId_ = getDefaultInstance().getAndroidId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string androidId = 4;</code>
       *
       * <pre>
       * android id converted to hexadecimal
       * </pre>
       */
      public Builder setAndroidIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        androidId_ = value;
        onChanged();
        return this;
      }

      // optional string deviceAndSdkVersion = 5;
      private java.lang.Object deviceAndSdkVersion_ = "";
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public boolean hasDeviceAndSdkVersion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public java.lang.String getDeviceAndSdkVersion() {
        java.lang.Object ref = deviceAndSdkVersion_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceAndSdkVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceAndSdkVersionBytes() {
        java.lang.Object ref = deviceAndSdkVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceAndSdkVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public Builder setDeviceAndSdkVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceAndSdkVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public Builder clearDeviceAndSdkVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceAndSdkVersion_ = getDefaultInstance().getDeviceAndSdkVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceAndSdkVersion = 5;</code>
       *
       * <pre>
       * ro.product.device ':' ro.build.version.sdk 
       * </pre>
       */
      public Builder setDeviceAndSdkVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceAndSdkVersion_ = value;
        onChanged();
        return this;
      }

      // optional string userLanguage = 6;
      private java.lang.Object userLanguage_ = "";
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public boolean hasUserLanguage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public java.lang.String getUserLanguage() {
        java.lang.Object ref = userLanguage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userLanguage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserLanguageBytes() {
        java.lang.Object ref = userLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public Builder setUserLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public Builder clearUserLanguage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userLanguage_ = getDefaultInstance().getUserLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userLanguage = 6;</code>
       *
       * <pre>
       * ro.product.locale.language
       * </pre>
       */
      public Builder setUserLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userLanguage_ = value;
        onChanged();
        return this;
      }

      // optional string userCountry = 7;
      private java.lang.Object userCountry_ = "";
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public boolean hasUserCountry() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public java.lang.String getUserCountry() {
        java.lang.Object ref = userCountry_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userCountry_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserCountryBytes() {
        java.lang.Object ref = userCountry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userCountry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public Builder setUserCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userCountry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public Builder clearUserCountry() {
        bitField0_ = (bitField0_ & ~0x00000040);
        userCountry_ = getDefaultInstance().getUserCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCountry = 7;</code>
       *
       * <pre>
       * ro.product.locale.region
       * </pre>
       */
      public Builder setUserCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userCountry_ = value;
        onChanged();
        return this;
      }

      // optional string operatorAlpha = 8;
      private java.lang.Object operatorAlpha_ = "";
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public boolean hasOperatorAlpha() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public java.lang.String getOperatorAlpha() {
        java.lang.Object ref = operatorAlpha_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          operatorAlpha_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOperatorAlphaBytes() {
        java.lang.Object ref = operatorAlpha_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operatorAlpha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public Builder setOperatorAlpha(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        operatorAlpha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public Builder clearOperatorAlpha() {
        bitField0_ = (bitField0_ & ~0x00000080);
        operatorAlpha_ = getDefaultInstance().getOperatorAlpha();
        onChanged();
        return this;
      }
      /**
       * <code>optional string operatorAlpha = 8;</code>
       *
       * <pre>
       * gsm.operator.alpha
       * </pre>
       */
      public Builder setOperatorAlphaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        operatorAlpha_ = value;
        onChanged();
        return this;
      }

      // optional string simOperatorAlpha = 9;
      private java.lang.Object simOperatorAlpha_ = "";
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public boolean hasSimOperatorAlpha() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public java.lang.String getSimOperatorAlpha() {
        java.lang.Object ref = simOperatorAlpha_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          simOperatorAlpha_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSimOperatorAlphaBytes() {
        java.lang.Object ref = simOperatorAlpha_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          simOperatorAlpha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public Builder setSimOperatorAlpha(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        simOperatorAlpha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public Builder clearSimOperatorAlpha() {
        bitField0_ = (bitField0_ & ~0x00000100);
        simOperatorAlpha_ = getDefaultInstance().getSimOperatorAlpha();
        onChanged();
        return this;
      }
      /**
       * <code>optional string simOperatorAlpha = 9;</code>
       *
       * <pre>
       * gsm.sim.operator.alpha
       * </pre>
       */
      public Builder setSimOperatorAlphaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        simOperatorAlpha_ = value;
        onChanged();
        return this;
      }

      // optional string operatorNumeric = 10;
      private java.lang.Object operatorNumeric_ = "";
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public boolean hasOperatorNumeric() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public java.lang.String getOperatorNumeric() {
        java.lang.Object ref = operatorNumeric_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          operatorNumeric_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOperatorNumericBytes() {
        java.lang.Object ref = operatorNumeric_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operatorNumeric_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public Builder setOperatorNumeric(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        operatorNumeric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public Builder clearOperatorNumeric() {
        bitField0_ = (bitField0_ & ~0x00000200);
        operatorNumeric_ = getDefaultInstance().getOperatorNumeric();
        onChanged();
        return this;
      }
      /**
       * <code>optional string operatorNumeric = 10;</code>
       *
       * <pre>
       * gsm.operator.numeric
       * </pre>
       */
      public Builder setOperatorNumericBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        operatorNumeric_ = value;
        onChanged();
        return this;
      }

      // optional string simOperatorNumeric = 11;
      private java.lang.Object simOperatorNumeric_ = "";
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public boolean hasSimOperatorNumeric() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public java.lang.String getSimOperatorNumeric() {
        java.lang.Object ref = simOperatorNumeric_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          simOperatorNumeric_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSimOperatorNumericBytes() {
        java.lang.Object ref = simOperatorNumeric_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          simOperatorNumeric_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public Builder setSimOperatorNumeric(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        simOperatorNumeric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public Builder clearSimOperatorNumeric() {
        bitField0_ = (bitField0_ & ~0x00000400);
        simOperatorNumeric_ = getDefaultInstance().getSimOperatorNumeric();
        onChanged();
        return this;
      }
      /**
       * <code>optional string simOperatorNumeric = 11;</code>
       *
       * <pre>
       * sim.gsm.operator.numeric
       * </pre>
       */
      public Builder setSimOperatorNumericBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        simOperatorNumeric_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:App)
    }

    static {
      defaultInstance = new App(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:App)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestContext_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestContext_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_App_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_App_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nPlay.proto\"#\n\016RequestContext\022\021\n\003app\030\001 " +
      "\003(\0132\004.App\"\377\001\n\003App\022\024\n\014authSubToken\030\001 \001(\014\022" +
      "\020\n\010isSecure\030\002 \001(\010\022\017\n\007version\030\003 \001(\005\022\021\n\tan" +
      "droidId\030\004 \001(\t\022\033\n\023deviceAndSdkVersion\030\005 \001" +
      "(\t\022\024\n\014userLanguage\030\006 \001(\t\022\023\n\013userCountry\030" +
      "\007 \001(\t\022\025\n\roperatorAlpha\030\010 \001(\t\022\030\n\020simOpera" +
      "torAlpha\030\t \001(\t\022\027\n\017operatorNumeric\030\n \001(\t\022" +
      "\032\n\022simOperatorNumeric\030\013 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RequestContext_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RequestContext_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RequestContext_descriptor,
              new java.lang.String[] { "App", });
          internal_static_App_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_App_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_App_descriptor,
              new java.lang.String[] { "AuthSubToken", "IsSecure", "Version", "AndroidId", "DeviceAndSdkVersion", "UserLanguage", "UserCountry", "OperatorAlpha", "SimOperatorAlpha", "OperatorNumeric", "SimOperatorNumeric", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
